/*
 * File: app/model/ProposalAsset.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.model.ProposalAsset', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.proxy.Rest',
        'Ext.data.field.Boolean',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            name: 'title'
        },
        {
            name: 'idassettype'
        },
        {
            name: 'idclient'
        },
        {
            name: 'clientname'
        },
        {
            name: 'description'
        },
        {
            name: 'fileurl'
        },
        {
            name: 'fullcontent'
        },
        {
            type: 'boolean',
            name: 'bwin'
        },
        {
            name: 'assettype'
        },
        {
            type: 'date',
            name: 'datedue',
            dateFormat: 'm/d/Y H:i'
        },
        {
            name: 'contenturl'
        },
        {
            name: 'updateuser'
        },
        {
            type: 'date',
            name: 'updatedate',
            dateFormat: 'm/d/Y H:i'
        },
        {
            name: 'taxonomy'
        },
        {
            name: 'tags'
        }
    ],

    proxy: {
        type: 'rest',
        url: '/rest/ProposalManager/Assets',
        withCredentials: true,
        format: 'json'
    }
});