/*
 * File: app/model/Tag.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.model.Tag', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Date',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'text'
        },
        {
            name: 'updateuser'
        },
        {
            type: 'date',
            name: 'updatedate',
            dateFormat: 'm/d/Y H:i'
        }
    ],

    proxy: {
        type: 'rest',
        url: '/rest/ProposalManager/Tags',
        withCredentials: true,
        format: 'json',
        reader: {
            type: 'json',
            rootProperty: 'records'
        }
    }
});