/*
 * File: app/model/User.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.model.User', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.Date',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            name: 'username',
            validations: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            name: 'password',
            validations: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            name: 'email',
            validations: [
                {
                    type: 'email'
                },
                {
                    type: 'presence'
                }
            ]
        },
        {
            name: 'idcompany',
            validations: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            type: 'int',
            name: 'idrole',
            validations: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            name: 'updateuser'
        },
        {
            type: 'date',
            name: 'updatedate',
            dateFormat: 'm/d/Y H:i'
        },
        {
            name: 'companyname'
        },
        {
            name: 'role'
        }
    ],

    proxy: {
        type: 'rest',
        url: '/rest/ProposalManager/User',
        withCredentials: true,
        format: 'json',
        reader: {
            type: 'json',
            rootProperty: 'records'
        },
        writer: {
            type: 'json',
            writeAllFields: true
        }
    }
});