/*
 * File: app/view/login/Login.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.login.Login', {
    extend: 'Ext.window.Window',
    alias: 'widget.login',

    requires: [
        'ProposalManager.view.login.LoginViewModel',
        'ProposalManager.view.login.LoginViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'loginlogin',
    viewModel: {
        type: 'loginlogin'
    },
    viewModel: null,
    autoShow: true,
    height: 150,
    width: 300,
    layout: 'fit',
    closable: false,
    title: 'Proposal Manager - Please Log In',
    modal: true,

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'User Name',
                    name: 'username',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Password',
                    name: 'password',
                    inputType: 'password',
                    allowBlank: false
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    layout: {
                        type: 'hbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            formBind: true,
                            text: 'Login',
                            listeners: {
                                click: 'onLogin'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});