/*
 * File: app/view/login/LoginViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.login.LoginViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.loginlogin',

    onLogin: function(button, e, eOpts) {
        var me = this;
        var form = button.up('form');
        var win = this.getView();
        var values = form.getValues();
        Ext.Ajax.request({
            url: '/rest/ProposalManager/Auth.json',
            jsonData: values,
            withCredentials: true,
            callback: function(req,success,response) {
                var res = Ext.decode(response.responseText);
                if (res.id == 0) {
                    Ext.Msg.alert(
                    "Invalid Credentials",
                    "Please try again"
                    );
                    form.reset();
                } else {

                    sessionStorage.setItem("userName",res.username);
                    sessionStorage.setItem("userRole",res.rolename);

                    if (me.getView().action) {

                        me.getView().action.resume();
                    } else {

                        me.redirectTo('main');
                    }
                    win.close();


                }
            }
        });
    }

});
