/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({

    requires: [
        'Ext.ux.form.TinyMCETextArea',
        'Shared.overrides.patches.data.writer.Writer'
    ],
    models: [
        'ProposalAsset',
        'Company',
        'User',
        'TaxonomyTerm',
        'Client',
        'Tag'
    ],
    stores: [
        'Roles',
        'Companies',
        'AssetTypes',
        'Clients',
        'Tags'
    ],
    views: [
        'categories.Select',
        'asset.Editor',
        'categories.Edit',
        'login.Login',
        'main.Viewport',
        'asset.Browser',
        'main.Toolbar',
        'admin.users.Users',
        'ux.TinyMce2',
        'admin.clients.Clients',
        'asset.Viewer',
        'asset.SearchForm',
        'admin.tags.Tags',
        'analytics.Analytics'
    ],
    controllers: [
        'Main'
    ],
    defaultToken: 'home',
    name: 'ProposalManager',

    launch: function() {
        Ext.create('ProposalManager.view.main.Viewport');
    }

});
