/*
 * File: app/view/main/Main.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.main.Main', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.main',

    requires: [
        'ProposalManager.view.main.MainViewModel',
        'ProposalManager.view.main.MainViewController',
        'ProposalManager.view.main.Toolbar',
        'ProposalManager.view.asset.Browser',
        'Ext.toolbar.Toolbar',
        'Ext.panel.Panel'
    ],

    controller: 'mainmain',
    viewModel: {
        type: 'mainmain'
    },
    viewModel: null,
    layout: 'border',

    items: [
        {
            xtype: 'maintoolbar',
            region: 'north'
        },
        {
            xtype: 'assetbrowser',
            region: 'center'
        }
    ],
    listeners: {
        beforerender: 'onPanelBeforeRender'
    }

});