/*
 * File: app/view/main/ToolbarViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.main.ToolbarViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.maintoolbar',

    onAdminMenuClick: function(menu, item, e, eOpts) {
        this.redirectTo('admin/' + item.itemId);
    },

    onLogoutButtonClick: function(button, e, eOpts) {

        Ext.Msg.confirm(
        "Logout?",
        "Are you sure that you want to log out?",
        function(b) {
            if (b == 'yes') {
                this.redirectTo("logout");
            }
        },
        this
        );
    }

});
