/*
 * File: app/view/main/Toolbar.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.main.Toolbar', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.maintoolbar',

    requires: [
        'ProposalManager.view.main.ToolbarViewModel',
        'ProposalManager.view.main.ToolbarViewController',
        'Ext.toolbar.TextItem',
        'Ext.toolbar.Fill',
        'Ext.button.Split',
        'Ext.menu.Menu',
        'Ext.menu.Separator'
    ],

    controller: 'maintoolbar',
    viewModel: {
        type: 'maintoolbar'
    },
    viewModel: null,
    height: 35,

    items: [
        {
            xtype: 'tbtext',
            cls: 'titletext',
            html: 'Proposal Manager'
        },
        {
            xtype: 'tbfill'
        },
        {
            xtype: 'splitbutton',
            text: 'Administration',
            menu: {
                xtype: 'menu',
                width: 160,
                items: [
                    {
                        xtype: 'menuitem',
                        itemId: 'adminclients',
                        text: 'Edit Clients',
                        bind: {
                            hidden: '{!isAdmin}'
                        }
                    },
                    {
                        xtype: 'menuitem',
                        itemId: 'editcategories',
                        text: 'Edit Categories',
                        bind: {
                            hidden: '{!isAdmin}'
                        }
                    },
                    {
                        xtype: 'menuitem',
                        itemId: 'admintags',
                        text: 'Edit Tags'
                    },
                    {
                        xtype: 'menuseparator'
                    },
                    {
                        xtype: 'menuitem',
                        itemId: 'analytics',
                        text: 'Production Chart'
                    },
                    {
                        xtype: 'menuseparator',
                        bind: {
                            hidden: '{!isSuperAdmin}'
                        }
                    },
                    {
                        xtype: 'menuitem',
                        itemId: 'admincompanies',
                        text: 'Edit Companies',
                        bind: {
                            hidden: '{!isSuperAdmin}'
                        }
                    },
                    {
                        xtype: 'menuitem',
                        itemId: 'adminusers',
                        text: 'Edit Users',
                        bind: {
                            hidden: '{!isSuperAdmin}'
                        }
                    }
                ],
                listeners: {
                    click: 'onAdminMenuClick'
                }
            }
        },
        {
            xtype: 'button',
            text: 'Logout',
            listeners: {
                click: 'onLogoutButtonClick'
            }
        }
    ]

});