/*
 * File: app/view/main/Viewport.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.main.Viewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainviewport',

    requires: [
        'ProposalManager.view.main.ViewportViewModel',
        'ProposalManager.view.main.Main'
    ],

    viewModel: {
        type: 'mainviewport'
    },
    cls: 'mainBackground',
    layout: 'fit'

});