/*
 * File: app/view/analytics/Analytics.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.analytics.Analytics', {
    extend: 'Ext.window.Window',
    alias: 'widget.analytics',

    requires: [
        'ProposalManager.view.analytics.AnalyticsViewModel',
        'ProposalManager.view.analytics.AnalyticsViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.form.field.Number',
        'Ext.view.Table',
        'Ext.grid.plugin.RowEditing',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category3D',
        'Ext.chart.axis.Numeric3D',
        'Ext.chart.series.Bar3D',
        'Ext.chart.Legend',
        'Ext.chart.axis.sprite.Axis3D',
        'Ext.chart.grid.VerticalGrid3D',
        'Ext.chart.grid.HorizontalGrid3D'
    ],

    controller: 'analyticsanalytics',
    viewModel: {
        type: 'analyticsanalytics'
    },
    autoShow: true,
    height: 416,
    width: 900,
    layout: 'border',
    title: 'Production vs. Wins',
    modal: true,

    items: [
        {
            xtype: 'gridpanel',
            region: 'west',
            split: true,
            width: 350,
            collapsible: true,
            header: false,
            title: 'Statistics',
            bind: {
                store: '{Analytics}'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'month',
                    text: 'Month',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'numbercolumn',
                    align: 'right',
                    dataIndex: 'wins',
                    text: 'Wins',
                    flex: 1,
                    format: '0,0',
                    editor: {
                        xtype: 'numberfield'
                    }
                },
                {
                    xtype: 'numbercolumn',
                    align: 'right',
                    dataIndex: 'losses',
                    text: 'Losses',
                    flex: 1,
                    format: '0,0'
                },
                {
                    xtype: 'numbercolumn',
                    align: 'right',
                    dataIndex: 'total',
                    text: 'Total',
                    flex: 1,
                    format: '0,0',
                    editor: {
                        xtype: 'numberfield'
                    }
                },
                {
                    xtype: 'numbercolumn',
                    align: 'right',
                    dataIndex: 'winpct',
                    text: 'Win %',
                    flex: 1
                }
            ],
            plugins: [
                {
                    ptype: 'rowediting'
                }
            ]
        },
        {
            xtype: 'cartesian',
            flex: 1,
            region: 'center',
            split: false,
            insetPadding: '40 20 10 20',
            bind: {
                store: '{Analytics}'
            },
            axes: [
                {
                    type: 'category3d',
                    grid: true,
                    position: 'bottom',
                    title: 'Month'
                },
                {
                    type: 'numeric3d',
                    grid: {
                        odd: {
                            fillStyle: 'rgba(255, 255, 255, 0.06)'
                        },
                        even: {
                            fillStyle: 'rgba(0, 0, 0, 0.03)'
                        }
                    },
                    position: 'left',
                    title: 'Proposals'
                }
            ],
            series: [
                {
                    type: 'bar3d',
                    xField: 'month',
                    yField: [
                        'losses',
                        'wins'
                    ]
                }
            ],
            legend: {
                xtype: 'legend'
            }
        }
    ],
    listeners: {
        close: 'onWindowClose'
    }

});