/*
 * File: app/view/analytics/AnalyticsViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.analytics.AnalyticsViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.analyticsanalytics',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json',
        'Ext.data.field.Number',
        'Ext.util.Sorter'
    ],

    stores: {
        Analytics: {
            autoLoad: true,
            proxy: {
                type: 'rest',
                url: '/rest/ProposalManager/WinRate',
                format: 'json',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'month'
                },
                {
                    type: 'int',
                    calculate: function(data) {
                        return data.total - data.wins;
                    },
                    name: 'losses'
                },
                {
                    type: 'int',
                    name: 'wins'
                },
                {
                    type: 'int',
                    name: 'total'
                },
                {
                    type: 'float',
                    calculate: function(data) {
                        return (data.wins / data.total) * 100;
                    },
                    name: 'winpct'
                }
            ],
            sorters: {
                property: 'month'
            }
        }
    }

});