/*
 * File: app/view/asset/Browser.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.asset.Browser', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.assetbrowser',

    requires: [
        'ProposalManager.view.asset.BrowserViewModel',
        'ProposalManager.view.asset.BrowserViewController',
        'ProposalManager.view.asset.Viewer',
        'ProposalManager.view.asset.SearchForm',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.view.Table',
        'Ext.grid.column.Action',
        'Ext.panel.Tool',
        'Ext.XTemplate',
        'Ext.form.Panel'
    ],

    controller: 'assetbrowser',
    viewModel: {
        type: 'assetbrowser'
    },
    layout: 'border',
    header: false,
    title: 'My Panel',

    items: [
        {
            xtype: 'gridpanel',
            flex: 1.5,
            region: 'center',
            split: true,
            collapsible: true,
            title: 'Assets (double-click to view)',
            allowDeselect: true,
            bind: {
                selection: '{selectedRecord}',
                store: '{ProposalAssets}'
            },
            columns: [
                {
                    xtype: 'datecolumn',
                    dataIndex: 'updatedate',
                    text: 'Updated'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'title',
                    text: 'Title',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    width: 90,
                    dataIndex: 'assettype',
                    text: 'Type'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'updateuser',
                    text: 'Updated By'
                },
                {
                    xtype: 'actioncolumn',
                    width: 60,
                    menuDisabled: true,
                    items: [
                        {
                            handler: 'onViewAsset',
                            icon: 'resources/images/view.png',
                            tooltip: 'View'
                        },
                        {
                            handler: 'onEditAsset',
                            icon: 'resources/images/document_edit.png',
                            tooltip: 'Edit'
                        },
                        {
                            handler: 'onDownloadAsset',
                            icon: 'resources/images/download.png',
                            tooltip: 'Download'
                        }
                    ]
                }
            ],
            tools: [
                {
                    xtype: 'tool',
                    tooltip: 'Add New Asset',
                    type: 'plus',
                    listeners: {
                        click: 'onNewAsset'
                    }
                },
                {
                    xtype: 'tool',
                    tooltip: 'Delete Asset',
                    type: 'minus',
                    bind: {
                        disabled: '{!selectedRecord}'
                    },
                    listeners: {
                        click: 'onDeleteClick'
                    }
                },
                {
                    xtype: 'tool',
                    type: 'refresh',
                    listeners: {
                        click: 'onRefresh'
                    }
                }
            ],
            listeners: {
                itemdblclick: 'onGridpanelItemDblClick'
            }
        },
        {
            xtype: 'panel',
            flex: 1,
            region: 'south',
            split: true,
            cls: 'metadatapanel',
            height: 150,
            tpl: [
                '<tpl if="title != \'\'">',
                '    <div class="label">Title:</div>{title}<br />',
                '    <div class="label">Type:</div>{assettype}<br />',
                '    <div class="label">Updated:</div>{updatedate:date}<br />',
                '    <div class="label">Description:</div><br />{description}',
                '</tpl>'
            ],
            bodyPadding: 5,
            collapsible: true,
            bind: {
                data: '{selectedRecord}',
                title: '{selectedRecord.title}'
            }
        },
        {
            xtype: 'assetviewer',
            collapsible: true,
            flex: 2,
            region: 'east',
            split: true,
            weight: 50
        },
        {
            xtype: 'assetsearchform',
            width: 250,
            collapsible: true,
            region: 'west',
            split: true,
            weight: 60
        }
    ]

});