/*
 * File: app/view/asset/BrowserViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.asset.BrowserViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.assetbrowser',

    requires: [
        'Ext.data.BufferedStore',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    data: {
        selectedRecord: null
    },

    stores: {
        ProposalAssets: {
            type: 'buffered',
            autoLoad: true,
            model: 'ProposalManager.model.ProposalAsset',
            proxy: {
                type: 'rest',
                url: '/rest/ProposalManager/Assets',
                withCredentials: true,
                format: 'json',
                reader: {
                    type: 'json',
                    rootProperty: 'records'
                }
            }
        }
    }

});