/*
 * File: app/view/asset/Editor.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.asset.Editor', {
    extend: 'Ext.window.Window',
    alias: 'widget.editasset',

    requires: [
        'ProposalManager.view.asset.EditorViewModel',
        'ProposalManager.view.asset.EditorViewController',
        'ProposalManager.view.ux.TinyMce2',
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.form.field.TextArea',
        'Ext.form.field.Tag',
        'Ext.form.field.File',
        'Ext.tab.Bar',
        'Ext.panel.Tool',
        'Ext.tree.Panel',
        'Ext.tree.View'
    ],

    config: {
        assetId: 0
    },

    controller: 'asseteditor',
    viewModel: {
        type: 'asseteditor'
    },
    autoShow: true,
    height: 515,
    width: 945,
    layout: 'border',
    title: 'Add Asset',
    modal: true,

    items: [
        {
            xtype: 'form',
            flex: 1,
            region: 'center',
            reference: 'theform',
            layout: 'fit',
            header: false,
            title: 'My Form',
            items: [
                {
                    xtype: 'tabpanel',
                    activeTab: 0,
                    deferredRender: false,
                    tabPosition: 'bottom',
                    items: [
                        {
                            xtype: 'panel',
                            defaults: {
                                anchor: '100%'
                            },
                            layout: 'anchor',
                            bodyPadding: 10,
                            title: 'Metadata',
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Asset Title',
                                    name: 'title',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Asset Type',
                                    name: 'idassettype',
                                    allowBlank: false,
                                    forceSelection: true,
                                    queryMode: 'local',
                                    store: 'AssetTypes',
                                    valueField: 'id',
                                    listeners: {
                                        change: 'onAssetTypeChange'
                                    }
                                },
                                {
                                    xtype: 'combobox',
                                    reference: 'idClient',
                                    fieldLabel: 'Client Name',
                                    name: 'idclient',
                                    displayField: 'clientname',
                                    store: 'Clients',
                                    valueField: 'id'
                                },
                                {
                                    xtype: 'datefield',
                                    reference: 'datedue',
                                    fieldLabel: 'Date Due',
                                    name: 'datedue'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    reference: 'bWin',
                                    fieldLabel: 'Win?',
                                    name: 'bwin',
                                    uncheckedValue: 'false'
                                },
                                {
                                    xtype: 'textareafield',
                                    height: 200,
                                    fieldLabel: 'Asset Description',
                                    labelAlign: 'top',
                                    name: 'description'
                                },
                                {
                                    xtype: 'tagfield',
                                    fieldLabel: 'Tags',
                                    name: 'tags',
                                    collapseOnSelect: true,
                                    queryMode: 'local',
                                    store: 'Tags',
                                    valueField: 'id',
                                    createNewOnBlur: true,
                                    createNewOnEnter: true
                                },
                                {
                                    xtype: 'filefield',
                                    hidden: true,
                                    fieldLabel: 'Upload File',
                                    name: 'uploadedfile'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Content URL',
                                    name: 'contenturl'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: 'fit',
                            title: 'Full Text',
                            items: [
                                {
                                    xtype: 'tinymce2',
                                    name: 'fullcontent'
                                }
                            ]
                        }
                    ],
                    tabBar: {
                        xtype: 'tabbar',
                        listeners: {
                            beforerender: 'onTabbarBeforeRender'
                        }
                    }
                }
            ],
            tools: [
                {
                    xtype: 'tool',
                    formBind: true,
                    type: 'save'
                }
            ]
        },
        {
            xtype: 'treepanel',
            region: 'west',
            split: true,
            reference: 'taxonomy',
            width: 250,
            collapsible: true,
            header: false,
            title: 'Taxonomy',
            rootVisible: false,
            bind: {
                store: '{Taxonomy}'
            }
        }
    ],
    listeners: {
        afterrender: 'onWindowAfterRender',
        close: 'onWindowClose'
    }

});