/*
 * File: app/view/asset/EditorViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.asset.EditorViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.asseteditor',

    requires: [
        'Ext.data.TreeStore',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    data: {
        selectedRecord: null
    },

    stores: {
        Taxonomy: {
            type: 'tree',
            root: {
                name: 'Root',
                expanded: true,
                children: [
                    
                ]
            },
            proxy: {
                type: 'rest',
                extraParams: {
                    checkboxes: true
                },
                url: '/rest/ProposalManager/Taxonomy',
                withCredentials: true,
                appendId: false,
                format: 'json',
                reader: {
                    type: 'json'
                }
            }
        }
    }

});