/*
 * File: app/view/asset/SearchForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.asset.SearchForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.assetsearchform',

    requires: [
        'ProposalManager.view.asset.SearchFormViewModel',
        'ProposalManager.view.asset.SearchFormViewController',
        'ProposalManager.view.categories.Select',
        'Ext.form.field.ComboBox',
        'Ext.tree.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'searchform',
    viewModel: {
        type: 'searchform'
    },
    viewModel: null,
    defaults: {
        margin: '5 5 0 5'
    },
    title: 'Search',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'combobox',
            fieldLabel: 'Label',
            hideLabel: true,
            name: 'idAssetType',
            emptyText: 'All Asset Types',
            forceSelection: true,
            queryMode: 'local',
            store: 'AssetTypes',
            valueField: 'id',
            listeners: {
                change: 'onAssetTypeSelect'
            }
        },
        {
            xtype: 'combobox',
            fieldLabel: 'Label',
            hideLabel: true,
            name: 'idClient',
            emptyText: 'All Clients',
            displayField: 'clientname',
            forceSelection: true,
            store: 'Clients',
            valueField: 'id',
            listeners: {
                change: 'onIdClientChange'
            }
        },
        {
            xtype: 'textfield',
            fieldLabel: '',
            hideLabel: true,
            name: 'searchtext',
            emptyText: 'Search Terms',
            listeners: {
                change: {
                    fn: 'onSearchTermChange',
                    buffer: 250
                }
            }
        },
        {
            xtype: 'categoriesselect',
            reference: 'taxonomytree',
            margin: '10 0 0 0',
            flex: 1,
            listeners: {
                checkchange: 'onTaxonomyCheckChange'
            }
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            flex: 1,
            dock: 'bottom',
            layout: {
                type: 'hbox',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    handler: 'onClearFilters',
                    text: 'Clear Filters'
                }
            ]
        }
    ]

});