/*
 * File: app/view/ux/TinyMce2.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.ux.TinyMce2', {
    extend: 'Ext.container.Container',
    alias: 'widget.tinymce2',

    requires: [
        'ProposalManager.view.ux.TinyMce2ViewModel'
    ],

    config: {
        name: ''
    },

    viewModel: {
        type: 'uxtinymce2'
    },
    height: 250,
    width: 400,
    layout: 'fit',
    defaultListenerScope: true,

    listeners: {
        beforerender: 'onContainerBeforeRender'
    },

    onContainerBeforeRender: function(component, eOpts) {
        component.add({
            xtype: 'tinymce',
            name: component.getName()
        });
    }

});