/*
 * File: app/view/categories/Edit.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.categories.Edit', {
    extend: 'Ext.window.Window',
    alias: 'widget.editcategories',

    requires: [
        'ProposalManager.view.categories.EditViewModel',
        'ProposalManager.view.categories.EditViewController',
        'Ext.panel.Tool',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.tree.plugin.TreeViewDragDrop',
        'Ext.tree.Column',
        'Ext.form.field.Text',
        'Ext.grid.plugin.CellEditing'
    ],

    controller: 'categoriesedit',
    viewModel: {
        type: 'categoriesedit'
    },
    autoShow: true,
    height: 500,
    width: 400,
    layout: 'fit',
    title: 'Category Editor',
    modal: true,

    tools: [
        {
            xtype: 'tool',
            callback: 'onAddNode',
            tooltip: 'Add New Node',
            type: 'plus',
            bind: {
                disabled: '{!selectedNode}'
            }
        },
        {
            xtype: 'tool',
            callback: 'onDeleteNode',
            tooltip: 'Delete Node',
            type: 'minus',
            bind: {
                disabled: '{!isRootSelected}'
            }
        },
        {
            xtype: 'tool',
            callback: 'onSaveTaxonomy',
            tooltip: 'Commit Changes',
            type: 'save'
        },
        {
            xtype: 'tool',
            callback: 'onRefresh',
            tooltip: 'Reload',
            type: 'refresh'
        }
    ],
    items: [
        {
            xtype: 'treepanel',
            plugins: [
                {
                    ptype: 'cellediting',
                    clicksToEdit: 2
                }
            ],
            header: false,
            title: 'Categories / Keywords',
            displayField: 'text',
            bind: {
                selection: '{selectedNode}',
                store: '{Taxonomy}'
            },
            viewConfig: {
                plugins: [
                    {
                        ptype: 'treeviewdragdrop',
                        appendOnly: true,
                        nodeHighlightOnDrop: true,
                        nodeHighlightOnRepair: true
                    }
                ]
            },
            columns: [
                {
                    xtype: 'treecolumn',
                    dataIndex: 'text',
                    text: 'Categories/Keywords',
                    flex: 1,
                    editor: {
                        xtype: 'textfield',
                        allowBlank: false,
                        allowOnlyWhitespace: false,
                        maxLength: 40
                    }
                }
            ],
            listeners: {
                edit: 'onNodeEdit'
            }
        }
    ],
    listeners: {
        close: 'onWindowClose'
    }

});