/*
 * File: app/view/admin/companies/Companies.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.admin.companies.Companies', {
    extend: 'Ext.window.Window',
    alias: 'widget.admincompanies',

    requires: [
        'ProposalManager.view.admin.companies.CompaniesViewModel',
        'ProposalManager.view.admin.companies.CompaniesViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.form.field.Text',
        'Ext.view.Table',
        'Ext.grid.plugin.RowEditing',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.TextItem',
        'Ext.panel.Tool'
    ],

    controller: 'admincompaniescompanies',
    viewModel: {
        type: 'admincompaniescompanies'
    },
    autoShow: true,
    height: 250,
    width: 400,
    layout: 'fit',
    title: 'Edit Companies',
    modal: true,

    items: [
        {
            xtype: 'gridpanel',
            reference: 'grid',
            header: false,
            title: '',
            store: 'Companies',
            bind: {
                selection: '{selectedRecord}'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'companyname',
                    text: 'Name',
                    flex: 1,
                    editor: {
                        xtype: 'textfield',
                        allowBlank: false
                    }
                }
            ],
            plugins: [
                {
                    ptype: 'rowediting',
                    pluginId: 'editor',
                    listeners: {
                        canceledit: 'onRowEditingCancelEdit',
                        edit: 'onRowEditingEdit'
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    reference: 'statusToolbar',
                    items: [
                        {
                            xtype: 'tbtext',
                            flex: 1,
                            height: 20,
                            bind: {
                                html: '{recordStatus}'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    tools: [
        {
            xtype: 'tool',
            tooltip: 'Add Company',
            type: 'plus',
            listeners: {
                click: 'onAddRecord'
            }
        },
        {
            xtype: 'tool',
            tooltip: 'Delete Company',
            type: 'minus',
            bind: {
                disabled: '{!selectedRecord}'
            },
            listeners: {
                click: 'onDeleteRecord'
            }
        },
        {
            xtype: 'tool',
            type: 'refresh',
            listeners: {
                click: 'onRefresh'
            }
        }
    ],
    listeners: {
        beforerender: 'onWindowBeforeRender',
        close: 'onWindowClose'
    }

});