/*
 * File: app/view/admin/companies/CompaniesViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProposalManager.view.admin.companies.CompaniesViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.admincompaniescompanies',

    requires: [
        'Ext.app.bind.Formula'
    ],

    data: {
        selectedRecord: null
    },

    formulas: {
        recordStatus: {
            get: function(data) {
                var rec = data;
                if (!rec || !Ext.isDate(rec.get('updatedate'))) {
                    return '';
                } else {
                    var msg = Ext.String.format(
                    "Last updated by {0} on {1}",
                    rec.get('updateuser'),
                    Ext.Date.format(rec.get('updatedate'),'m/d/Y @ H:i')
                    );
                    return msg;
                }
            },
            bind: {
                bindTo: '{selectedRecord}',
                deep: true
            }
        }
    }

});